
package vista;

import controlador.ContactoController;
import modelo.Contacto;
import modelo.ContactoModel;


// MODIFICA LA VISTA DE CONTACTOVIEWIMPL

public class ContactoViewImpl extends javax.swing.JFrame implements ContactoView {
    //Atributos del MVC

    private ContactoModel model;
    private ContactoController controller;

    //Atributos propios de Swing
    private ContactosTableModel tableModel;
    private JPanelContacto panelContacto;

    /** Creates new form VentanaPrincipal */
    public ContactoViewImpl() {
        tableModel = new ContactosTableModel();
        initComponents();

        this.panelContacto = new JPanelContacto(this);
        this.jPanelDown.add(this.panelContacto);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de Contactos");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 578, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 494, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ContactoViewImpl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables


}
